---
- name: Some packages
  hosts: debian_based

  tasks:
   - name: System update
     become: true
     ansible.builtin.apt:
        update_cache: true
   
   - name: Install basic packages
     become: true
     ansible.builtin.apt:
        name: "{{ item }}"
        state: present
     with_items:
        - sudo
        - vim
        - bash
        - systemd
        - coreutils
        
        
   - name: Install basic software
     become: true
     ansible.builtin.apt:
        name: "{{ item }}"
        state: present
     with_items:
        - ansible
        - docker.io
        - git
        
             	
   - name: Check if python is installed
     ansible.builtin.command: python3 --version
     register: python_check
     changed_when: false
     ignore_errors: true
     
   - name: Install python
     ansible.builtin.apt:
        name: python3
        state: present
        
   - name: Install pip
     ansible.builtin.apt:
        name: pip
        state: present
        
   - name: Install python libraries
     become: true
     ansible.builtin.pip:
        break_system_packages: true
        name: "{{ item }}"
     with_items:
        - bottle
        - pygame
        - poetry
        - requests
        
        
   - name: Install network analysis tools
     ansible.builtin.apt:
        name: "{{ item }}"
        state: present
     with_items:
        - wireshark-qt
        - nmap
        - iperf3
     when:
        - ansible_facts['distribution'] == "Debian"
        
        
        
